#!/bin/bash
# Задача 5: 

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "Использование: $0 <программа>" >&2
    exit 1
fi

PROG="$1"
DEST_DIR="/usr/local/bin"

if [ ! -f "$PROG" ]; then
    echo "Ошибка: файл '$PROG' не найден" >&2
    exit 1
fi


if [ -w "$DEST_DIR" ]; then
    cp -f "$PROG" "$DEST_DIR/"
else
    sudo cp -f "$PROG" "$DEST_DIR/"
fi

BASENAME=$(basename "$PROG")
echo "Команда '$BASENAME' зарегистрирована в $DEST_DIR и готова к использованию."
